services:
  mongo:
    image: "mongo:3.6"
    command: --wiredTigerCacheSizeGB 1 --smallfiles
    volumes:
      - "./volumes/mongo/data/db:/data/db"
    restart: unless-stopped
  controller:
    build:
      context: .
      args:
        UNIFI_CONTROLLER_VERSION: "8.0.28-66495b8e3a"
    hostname: unifi
    domainname: seathegood.net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3478:3478/udp"
      - "5514:5514/udp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8880:8880/tcp"
      - "8843:8843/tcp"
      - "6789:6789/tcp"
      - "27117:27117/tcp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "123:123/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./volumes/controller/cert:/usr/lib/unifi/cert"
      - "./volumes/controller/data:/usr/lib/unifi/data"
      - "./volumes/controller/logs:/usr/lib/unifi/logs"
    environment:
      - "DB_MONGO_LOCAL=false"
      - "DB_MONGO_URI=mongodb://mongo:27017/unifi"
      - "STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat"
      - "TZ=America/Chicago"
      - "UNIFI_DB_NAME=unifi"
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  frontend:
    external: true
    name: macvlan99
  backend:
    internal: true