services:
  mongo:
    image: "mongo:4.4"
    command: --journal --wiredTigerCacheSizeGB 1
    volumes:
      - "./mongo/data/db:/data/db"
    restart: unless-stopped
  controller:
    build:
      context: .
      args:
        UNIFI_CONTROLLER_VERSION: "8.1.104-75ec9ec4f1"
    hostname: unifi
    domainname: seathegood.net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3478:3478/udp"
      - "5514:5514/udp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8880:8880/tcp"
      - "8843:8843/tcp"
      - "6789:6789/tcp"
      - "27117:27117/tcp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "123:123/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./unifi-controller/cert:/usr/lib/unifi/cert"
      - "./unifi-controller/data:/usr/lib/unifi/data"
      - "./unifi-controller/logs:/usr/lib/unifi/logs"
    environment:
      - "DB_MONGO_LOCAL=false"
      - "DB_MONGO_URI=mongodb://mongo:27017/unifi"
      - "STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat"
      - "TZ=America/Chicago"
      - "UNIFI_DB_NAME=unifi"
    depends_on:
      - mongo
    restart: unless-stopped