name: Build

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - build.sh
      - docker-compose.yml
      - entrypoint.sh
      - entrypoint-functions.sh
      - healthcheck.sh
      - system.properties.default
      - .github/workflows/build.yml
      - .github/scripts/**
      - versions.txt
  pull_request:
    paths:
      - Dockerfile
      - build.sh
      - docker-compose.yml
      - entrypoint.sh
      - entrypoint-functions.sh
      - healthcheck.sh
      - system.properties.default
      - .github/workflows/build.yml
      - .github/scripts/**
      - versions.txt
  workflow_dispatch:

env:
  IMAGE_NAME: seathegood/unifi-controller

jobs:
  build:
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=Unifi Controller
            org.opencontainers.image.description=Unifi Controller without a local MongoDB instance
            org.opencontainers.image.vendor=Sea the Good, LLC
            org.opencontainers.image.licenses=MIT

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build image (multi-arch cache prime)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.created }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build image for smoke tests (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:ci-test-${{ github.sha }}
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.created }}
            VCS_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          labels: ${{ steps.meta.outputs.labels }}

      - name: Smoke test image
        run: |
          set -euo pipefail
          docker run --rm --entrypoint bash ${{ env.IMAGE_NAME }}:ci-test-${{ github.sha }} \
            -c "dpkg -s unifi | grep -i '^Version'"
