name: Sync Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/sync-dockerhub-readme.yml

jobs:
  sync:
    if: github.repository_owner == 'seathegood'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: seathegood/unifi-controller
          readme-filepath: README.md
